# Alexander Puchalski, arp248, IT202-project, 2026-02-10

POST http://localhost:3000/addgenre.test.php
Content-Type: application/x-www-form-urlencoded

genreID=4
&genreCode=clwn
&genreName=clown encyclopedia
###
GET http://localhost:3000/listgenre.test.php
###
POST http://localhost:3000/changegenre.test.php
Content-Type: application/x-www-form-urlencoded

genreID=4
&genreCode=futh
&genreName=future history
###
POST http://localhost:3000/removegenre.test.php
Content-Type: application/x-www-form-urlencoded

genreID=4